### ISSUE TITLE
IO ERROR

### ISSUE THREAD

**Issue by feiqingbiss** [capntrips/KernelFlasher#13]
![Screenshot_2023-08-23-13-53-23-245_bin mt plus](https://github.com/capntrips/KernelFlasher/assets/36787768/56d628dc-6ca4-47b7-a354-2ba3f1b20553)

ver alpha14
phone Android13 xiaomi13pro 
kernelsu 0.6.7
kernel 5.15.74 oem

**Comment by capntrips** [comment]
Can you share a logcat at the time of the error? Also, what file are you attempting to flash when you get that error? Is it a valid zip file?

**Comment by capntrips** [comment]
I'm going to close this for lack of info, but feel free to reopen and provide logs and additional details.
