### ISSUE TITLE
Version naming issue when app is managed with Obtainium

### ISSUE THREAD

**Issue by xfzv** [capntrips/KernelFlasher#3]
I'm using [Obtainium](https://github.com/ImranR98/Obtainium/issues) to directly get apps from source.

As I'm writing, the latest KernelFlasher version is [`v1.0.0-alpha012`](https://github.com/capntrips/KernelFlasher/releases/tag/v1.0.0-alpha012), but it seems that the version becomes `1.0.0-alpha12` when installed. 

As a result, Obtainium always thinks that there's an update available because the two names differ:

![1](https://user-images.githubusercontent.com/78810647/215513611-7ebd7a87-8087-4c47-8a3d-d082cae2dcd8.png)

Any chance you could fix that?

Thanks.

**Comment by capntrips** [comment]
It has been over a year, so I don't remember the specifics of why the change was made, but I originally omitted the `v` prefix from tags in one of my earlier apps but ended up needing it for something.

From [here](https://github.com/ImranR98/Obtainium/pull/144), it appears that Obtainium uses semver:

> This approach works for the majority of Apps, based on the version name format (a subset of [semver](https://semver.org/)).

semver's docs address this scenario:

https://semver.org/#is-v123-a-semantic-version

My suggestion would be to open a feature request or PR with Obtainium to handle this case, as I imagine it would be fairly common.

I'm going to close this for now, but I'll keep it in mind, in case an old memory rattles loose.

**Comment by capntrips** [comment]
I also only noticed the 0 in alpha*0*12 last night and removed it. Maybe that was part of the problem.
